sonar.projectKey=TaskManagement-Frontend
sonar.projectName=TaskManagement-Frontend
sonar.projectVersion=1.0
sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.exclusions=node_modules/**, dist/**, **/*.test.tsx, **/*.test.ts

# This line is CRITICAL to stop it from going to sonarcloud.io
sonar.host.url=http://localhost:9000
sonar.token=squ_51dd9aa51254a196b8abc3ce50571270ce408512